version: 2
jobs:
  build:
    docker:
      - image: golang:1.13-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build Docker image      
      - run:
          name: build Docker image
          command: |
            docker info
            docker build .
