version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build Docker image      
      - run:
          name: build Docker image
          command: |
            docker info
            docker build .
