version: 2
jobs:
  build:
    docker:
      - image: golang:1.13-stretch
    steps:
      - checkout
      - setup_remote_docker
      # build Docker image      
      - run:
          name: build Docker image
          command: |
            docker info
            docker build .
